# Generated by Django 3.2.9 on 2022-01-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBandmates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('genero', models.CharField(max_length=30, verbose_name='genero')),
                ('integrantes', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
