# Generated by Django 3.2.9 on 2022-01-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBandmates', '0002_banda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('edad', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Musico',
        ),
    ]
